prefix = "./cranfield/"
stop-words = "./cranfield/stopwords.txt"

dataset = "cranfield"
corpus = "line.toml"
index = "./cranfield/cranfield/idx"

query-judgments = "./cranfield/cranfield/cranfield-qrels.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "cranfield-queries.txt"
query-id-start = 1
